/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as BlogTagSlugRouteImport } from './routes/blog.tag.$slug'
import { Route as BlogCSlugRouteImport } from './routes/blog.c.$slug'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated.dashboard.settings'
import { Route as AuthenticatedDashboardProxiesRouteImport } from './routes/_authenticated.dashboard.proxies'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated.dashboard.orders'
import { Route as AuthenticatedDashboardNotificacoesRouteImport } from './routes/_authenticated.dashboard.notificacoes'
import { Route as AuthenticatedAdminProviderRouteImport } from './routes/_authenticated.admin.provider'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated.admin.pricing'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated.admin.orders'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated.admin.equipe'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated.admin.emails'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated.admin.customers'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated.admin.cupons'
import { Route as AuthenticatedAdminCloudRouteImport } from './routes/_authenticated.admin.cloud'
import { Route as AuthenticatedAdminChatRouteImport } from './routes/_authenticated.admin.chat'
import { Route as AuthenticatedAdminBroadcastRouteImport } from './routes/_authenticated.admin.broadcast'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated.admin.blog'
import { Route as AuthenticatedAdminAllocationsRouteImport } from './routes/_authenticated.admin.allocations'
import { Route as AuthenticatedAdminInventoryIndexRouteImport } from './routes/_authenticated.admin.inventory.index'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated.admin.blog.index'
import { Route as ApiPublicHooksStripeSyncRouteImport } from './routes/api/public/hooks/stripe-sync'
import { Route as ApiPublicHooksProxysellerSyncRouteImport } from './routes/api/public/hooks/proxyseller-sync'
import { Route as ApiPublicHooksProxysellerBackfillRouteImport } from './routes/api/public/hooks/proxyseller-backfill'
import { Route as ApiPublicHooksNotificationsDispatchRouteImport } from './routes/api/public/hooks/notifications-dispatch'
import { Route as ApiPublicHooksEngagementNudgesRouteImport } from './routes/api/public/hooks/engagement-nudges'
import { Route as ApiPublicHooksE2eRunnerRouteImport } from './routes/api/public/hooks/e2e-runner'
import { Route as ApiPublicCronHealthcheckRouteImport } from './routes/api/public/cron.healthcheck'
import { Route as AuthenticatedAdminInventoryProductIdRouteImport } from './routes/_authenticated.admin.inventory.$productId'
import { Route as AuthenticatedAdminCustomersUserIdRouteImport } from './routes/_authenticated.admin.customers.$userId'
import { Route as AuthenticatedAdminBlogTagsRouteImport } from './routes/_authenticated.admin.blog.tags'
import { Route as AuthenticatedAdminBlogProgramaticasRouteImport } from './routes/_authenticated.admin.blog.programaticas'
import { Route as AuthenticatedAdminBlogNewRouteImport } from './routes/_authenticated.admin.blog.new'
import { Route as AuthenticatedAdminBlogComentariosRouteImport } from './routes/_authenticated.admin.blog.comentarios'
import { Route as AuthenticatedAdminBlogCategoriasRouteImport } from './routes/_authenticated.admin.blog.categorias'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated.admin.blog.$id'
import { Route as AuthenticatedDashboardProxyIdQuickRouteImport } from './routes/_authenticated.dashboard.proxy.$id.quick'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const BlogTagSlugRoute = BlogTagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogCSlugRoute = BlogCSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardProxiesRoute =
  AuthenticatedDashboardProxiesRouteImport.update({
    id: '/dashboard/proxies',
    path: '/dashboard/proxies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/dashboard/orders',
    path: '/dashboard/orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardNotificacoesRoute =
  AuthenticatedDashboardNotificacoesRouteImport.update({
    id: '/dashboard/notificacoes',
    path: '/dashboard/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProviderRoute =
  AuthenticatedAdminProviderRouteImport.update({
    id: '/provider',
    path: '/provider',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/cupons',
    path: '/cupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCloudRoute = AuthenticatedAdminCloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminChatRoute = AuthenticatedAdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBroadcastRoute =
  AuthenticatedAdminBroadcastRouteImport.update({
    id: '/broadcast',
    path: '/broadcast',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAllocationsRoute =
  AuthenticatedAdminAllocationsRouteImport.update({
    id: '/allocations',
    path: '/allocations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInventoryIndexRoute =
  AuthenticatedAdminInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)
const ApiPublicHooksStripeSyncRoute =
  ApiPublicHooksStripeSyncRouteImport.update({
    id: '/api/public/hooks/stripe-sync',
    path: '/api/public/hooks/stripe-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProxysellerSyncRoute =
  ApiPublicHooksProxysellerSyncRouteImport.update({
    id: '/api/public/hooks/proxyseller-sync',
    path: '/api/public/hooks/proxyseller-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProxysellerBackfillRoute =
  ApiPublicHooksProxysellerBackfillRouteImport.update({
    id: '/api/public/hooks/proxyseller-backfill',
    path: '/api/public/hooks/proxyseller-backfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotificationsDispatchRoute =
  ApiPublicHooksNotificationsDispatchRouteImport.update({
    id: '/api/public/hooks/notifications-dispatch',
    path: '/api/public/hooks/notifications-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEngagementNudgesRoute =
  ApiPublicHooksEngagementNudgesRouteImport.update({
    id: '/api/public/hooks/engagement-nudges',
    path: '/api/public/hooks/engagement-nudges',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksE2eRunnerRoute = ApiPublicHooksE2eRunnerRouteImport.update({
  id: '/api/public/hooks/e2e-runner',
  path: '/api/public/hooks/e2e-runner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronHealthcheckRoute =
  ApiPublicCronHealthcheckRouteImport.update({
    id: '/api/public/cron/healthcheck',
    path: '/api/public/cron/healthcheck',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminInventoryProductIdRoute =
  AuthenticatedAdminInventoryProductIdRouteImport.update({
    id: '/inventory/$productId',
    path: '/inventory/$productId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersUserIdRoute =
  AuthenticatedAdminCustomersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminCustomersRoute,
  } as any)
const AuthenticatedAdminBlogTagsRoute =
  AuthenticatedAdminBlogTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)
const AuthenticatedAdminBlogProgramaticasRoute =
  AuthenticatedAdminBlogProgramaticasRouteImport.update({
    id: '/programaticas',
    path: '/programaticas',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)
const AuthenticatedAdminBlogNewRoute =
  AuthenticatedAdminBlogNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)
const AuthenticatedAdminBlogComentariosRoute =
  AuthenticatedAdminBlogComentariosRouteImport.update({
    id: '/comentarios',
    path: '/comentarios',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)
const AuthenticatedAdminBlogCategoriasRoute =
  AuthenticatedAdminBlogCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)
const AuthenticatedDashboardProxyIdQuickRoute =
  AuthenticatedDashboardProxyIdQuickRouteImport.update({
    id: '/dashboard/proxy/$id/quick',
    path: '/dashboard/proxy/$id/quick',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/allocations': typeof AuthenticatedAdminAllocationsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRouteWithChildren
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/chat': typeof AuthenticatedAdminChatRoute
  '/admin/cloud': typeof AuthenticatedAdminCloudRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/provider': typeof AuthenticatedAdminProviderRoute
  '/dashboard/notificacoes': typeof AuthenticatedDashboardNotificacoesRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/proxies': typeof AuthenticatedDashboardProxiesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/blog/c/$slug': typeof BlogCSlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/categorias': typeof AuthenticatedAdminBlogCategoriasRoute
  '/admin/blog/comentarios': typeof AuthenticatedAdminBlogComentariosRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/admin/blog/programaticas': typeof AuthenticatedAdminBlogProgramaticasRoute
  '/admin/blog/tags': typeof AuthenticatedAdminBlogTagsRoute
  '/admin/customers/$userId': typeof AuthenticatedAdminCustomersUserIdRoute
  '/admin/inventory/$productId': typeof AuthenticatedAdminInventoryProductIdRoute
  '/api/public/cron/healthcheck': typeof ApiPublicCronHealthcheckRoute
  '/api/public/hooks/e2e-runner': typeof ApiPublicHooksE2eRunnerRoute
  '/api/public/hooks/engagement-nudges': typeof ApiPublicHooksEngagementNudgesRoute
  '/api/public/hooks/notifications-dispatch': typeof ApiPublicHooksNotificationsDispatchRoute
  '/api/public/hooks/proxyseller-backfill': typeof ApiPublicHooksProxysellerBackfillRoute
  '/api/public/hooks/proxyseller-sync': typeof ApiPublicHooksProxysellerSyncRoute
  '/api/public/hooks/stripe-sync': typeof ApiPublicHooksStripeSyncRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/inventory/': typeof AuthenticatedAdminInventoryIndexRoute
  '/dashboard/proxy/$id/quick': typeof AuthenticatedDashboardProxyIdQuickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/blog': typeof BlogIndexRoute
  '/admin/allocations': typeof AuthenticatedAdminAllocationsRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/chat': typeof AuthenticatedAdminChatRoute
  '/admin/cloud': typeof AuthenticatedAdminCloudRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/provider': typeof AuthenticatedAdminProviderRoute
  '/dashboard/notificacoes': typeof AuthenticatedDashboardNotificacoesRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/proxies': typeof AuthenticatedDashboardProxiesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/blog/c/$slug': typeof BlogCSlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/categorias': typeof AuthenticatedAdminBlogCategoriasRoute
  '/admin/blog/comentarios': typeof AuthenticatedAdminBlogComentariosRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/admin/blog/programaticas': typeof AuthenticatedAdminBlogProgramaticasRoute
  '/admin/blog/tags': typeof AuthenticatedAdminBlogTagsRoute
  '/admin/customers/$userId': typeof AuthenticatedAdminCustomersUserIdRoute
  '/admin/inventory/$productId': typeof AuthenticatedAdminInventoryProductIdRoute
  '/api/public/cron/healthcheck': typeof ApiPublicCronHealthcheckRoute
  '/api/public/hooks/e2e-runner': typeof ApiPublicHooksE2eRunnerRoute
  '/api/public/hooks/engagement-nudges': typeof ApiPublicHooksEngagementNudgesRoute
  '/api/public/hooks/notifications-dispatch': typeof ApiPublicHooksNotificationsDispatchRoute
  '/api/public/hooks/proxyseller-backfill': typeof ApiPublicHooksProxysellerBackfillRoute
  '/api/public/hooks/proxyseller-sync': typeof ApiPublicHooksProxysellerSyncRoute
  '/api/public/hooks/stripe-sync': typeof ApiPublicHooksStripeSyncRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryIndexRoute
  '/dashboard/proxy/$id/quick': typeof AuthenticatedDashboardProxyIdQuickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/allocations': typeof AuthenticatedAdminAllocationsRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRouteWithChildren
  '/_authenticated/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/_authenticated/admin/chat': typeof AuthenticatedAdminChatRoute
  '/_authenticated/admin/cloud': typeof AuthenticatedAdminCloudRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/_authenticated/admin/provider': typeof AuthenticatedAdminProviderRoute
  '/_authenticated/dashboard/notificacoes': typeof AuthenticatedDashboardNotificacoesRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/proxies': typeof AuthenticatedDashboardProxiesRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/blog/c/$slug': typeof BlogCSlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/_authenticated/admin/blog/categorias': typeof AuthenticatedAdminBlogCategoriasRoute
  '/_authenticated/admin/blog/comentarios': typeof AuthenticatedAdminBlogComentariosRoute
  '/_authenticated/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/_authenticated/admin/blog/programaticas': typeof AuthenticatedAdminBlogProgramaticasRoute
  '/_authenticated/admin/blog/tags': typeof AuthenticatedAdminBlogTagsRoute
  '/_authenticated/admin/customers/$userId': typeof AuthenticatedAdminCustomersUserIdRoute
  '/_authenticated/admin/inventory/$productId': typeof AuthenticatedAdminInventoryProductIdRoute
  '/api/public/cron/healthcheck': typeof ApiPublicCronHealthcheckRoute
  '/api/public/hooks/e2e-runner': typeof ApiPublicHooksE2eRunnerRoute
  '/api/public/hooks/engagement-nudges': typeof ApiPublicHooksEngagementNudgesRoute
  '/api/public/hooks/notifications-dispatch': typeof ApiPublicHooksNotificationsDispatchRoute
  '/api/public/hooks/proxyseller-backfill': typeof ApiPublicHooksProxysellerBackfillRoute
  '/api/public/hooks/proxyseller-sync': typeof ApiPublicHooksProxysellerSyncRoute
  '/api/public/hooks/stripe-sync': typeof ApiPublicHooksStripeSyncRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/inventory/': typeof AuthenticatedAdminInventoryIndexRoute
  '/_authenticated/dashboard/proxy/$id/quick': typeof AuthenticatedDashboardProxyIdQuickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/privacidade'
    | '/reembolso'
    | '/reset-password'
    | '/rss.xml'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/admin'
    | '/blog/$slug'
    | '/checkout/success'
    | '/blog/'
    | '/admin/allocations'
    | '/admin/blog'
    | '/admin/broadcast'
    | '/admin/chat'
    | '/admin/cloud'
    | '/admin/cupons'
    | '/admin/customers'
    | '/admin/emails'
    | '/admin/equipe'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/provider'
    | '/dashboard/notificacoes'
    | '/dashboard/orders'
    | '/dashboard/proxies'
    | '/dashboard/settings'
    | '/api/public/stripe-webhook'
    | '/blog/c/$slug'
    | '/blog/tag/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/admin/blog/$id'
    | '/admin/blog/categorias'
    | '/admin/blog/comentarios'
    | '/admin/blog/new'
    | '/admin/blog/programaticas'
    | '/admin/blog/tags'
    | '/admin/customers/$userId'
    | '/admin/inventory/$productId'
    | '/api/public/cron/healthcheck'
    | '/api/public/hooks/e2e-runner'
    | '/api/public/hooks/engagement-nudges'
    | '/api/public/hooks/notifications-dispatch'
    | '/api/public/hooks/proxyseller-backfill'
    | '/api/public/hooks/proxyseller-sync'
    | '/api/public/hooks/stripe-sync'
    | '/admin/blog/'
    | '/admin/inventory/'
    | '/dashboard/proxy/$id/quick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/privacidade'
    | '/reembolso'
    | '/reset-password'
    | '/rss.xml'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/blog/$slug'
    | '/checkout/success'
    | '/blog'
    | '/admin/allocations'
    | '/admin/broadcast'
    | '/admin/chat'
    | '/admin/cloud'
    | '/admin/cupons'
    | '/admin/customers'
    | '/admin/emails'
    | '/admin/equipe'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/provider'
    | '/dashboard/notificacoes'
    | '/dashboard/orders'
    | '/dashboard/proxies'
    | '/dashboard/settings'
    | '/api/public/stripe-webhook'
    | '/blog/c/$slug'
    | '/blog/tag/$slug'
    | '/admin'
    | '/dashboard'
    | '/admin/blog/$id'
    | '/admin/blog/categorias'
    | '/admin/blog/comentarios'
    | '/admin/blog/new'
    | '/admin/blog/programaticas'
    | '/admin/blog/tags'
    | '/admin/customers/$userId'
    | '/admin/inventory/$productId'
    | '/api/public/cron/healthcheck'
    | '/api/public/hooks/e2e-runner'
    | '/api/public/hooks/engagement-nudges'
    | '/api/public/hooks/notifications-dispatch'
    | '/api/public/hooks/proxyseller-backfill'
    | '/api/public/hooks/proxyseller-sync'
    | '/api/public/hooks/stripe-sync'
    | '/admin/blog'
    | '/admin/inventory'
    | '/dashboard/proxy/$id/quick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blog'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/privacidade'
    | '/reembolso'
    | '/reset-password'
    | '/rss.xml'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/checkout/success'
    | '/blog/'
    | '/_authenticated/admin/allocations'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/broadcast'
    | '/_authenticated/admin/chat'
    | '/_authenticated/admin/cloud'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/provider'
    | '/_authenticated/dashboard/notificacoes'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/proxies'
    | '/_authenticated/dashboard/settings'
    | '/api/public/stripe-webhook'
    | '/blog/c/$slug'
    | '/blog/tag/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/admin/blog/$id'
    | '/_authenticated/admin/blog/categorias'
    | '/_authenticated/admin/blog/comentarios'
    | '/_authenticated/admin/blog/new'
    | '/_authenticated/admin/blog/programaticas'
    | '/_authenticated/admin/blog/tags'
    | '/_authenticated/admin/customers/$userId'
    | '/_authenticated/admin/inventory/$productId'
    | '/api/public/cron/healthcheck'
    | '/api/public/hooks/e2e-runner'
    | '/api/public/hooks/engagement-nudges'
    | '/api/public/hooks/notifications-dispatch'
    | '/api/public/hooks/proxyseller-backfill'
    | '/api/public/hooks/proxyseller-sync'
    | '/api/public/hooks/stripe-sync'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/inventory/'
    | '/_authenticated/dashboard/proxy/$id/quick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReembolsoRoute: typeof ReembolsoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicCronHealthcheckRoute: typeof ApiPublicCronHealthcheckRoute
  ApiPublicHooksE2eRunnerRoute: typeof ApiPublicHooksE2eRunnerRoute
  ApiPublicHooksEngagementNudgesRoute: typeof ApiPublicHooksEngagementNudgesRoute
  ApiPublicHooksNotificationsDispatchRoute: typeof ApiPublicHooksNotificationsDispatchRoute
  ApiPublicHooksProxysellerBackfillRoute: typeof ApiPublicHooksProxysellerBackfillRoute
  ApiPublicHooksProxysellerSyncRoute: typeof ApiPublicHooksProxysellerSyncRoute
  ApiPublicHooksStripeSyncRoute: typeof ApiPublicHooksStripeSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/blog/tag/$slug': {
      id: '/blog/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/blog/tag/$slug'
      preLoaderRoute: typeof BlogTagSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/c/$slug': {
      id: '/blog/c/$slug'
      path: '/c/$slug'
      fullPath: '/blog/c/$slug'
      preLoaderRoute: typeof BlogCSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/proxies': {
      id: '/_authenticated/dashboard/proxies'
      path: '/dashboard/proxies'
      fullPath: '/dashboard/proxies'
      preLoaderRoute: typeof AuthenticatedDashboardProxiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/notificacoes': {
      id: '/_authenticated/dashboard/notificacoes'
      path: '/dashboard/notificacoes'
      fullPath: '/dashboard/notificacoes'
      preLoaderRoute: typeof AuthenticatedDashboardNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/provider': {
      id: '/_authenticated/admin/provider'
      path: '/provider'
      fullPath: '/admin/provider'
      preLoaderRoute: typeof AuthenticatedAdminProviderRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cloud': {
      id: '/_authenticated/admin/cloud'
      path: '/cloud'
      fullPath: '/admin/cloud'
      preLoaderRoute: typeof AuthenticatedAdminCloudRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chat': {
      id: '/_authenticated/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AuthenticatedAdminChatRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/broadcast': {
      id: '/_authenticated/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AuthenticatedAdminBroadcastRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/allocations': {
      id: '/_authenticated/admin/allocations'
      path: '/allocations'
      fullPath: '/admin/allocations'
      preLoaderRoute: typeof AuthenticatedAdminAllocationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventory/': {
      id: '/_authenticated/admin/inventory/'
      path: '/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AuthenticatedAdminInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
    '/api/public/hooks/stripe-sync': {
      id: '/api/public/hooks/stripe-sync'
      path: '/api/public/hooks/stripe-sync'
      fullPath: '/api/public/hooks/stripe-sync'
      preLoaderRoute: typeof ApiPublicHooksStripeSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/proxyseller-sync': {
      id: '/api/public/hooks/proxyseller-sync'
      path: '/api/public/hooks/proxyseller-sync'
      fullPath: '/api/public/hooks/proxyseller-sync'
      preLoaderRoute: typeof ApiPublicHooksProxysellerSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/proxyseller-backfill': {
      id: '/api/public/hooks/proxyseller-backfill'
      path: '/api/public/hooks/proxyseller-backfill'
      fullPath: '/api/public/hooks/proxyseller-backfill'
      preLoaderRoute: typeof ApiPublicHooksProxysellerBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notifications-dispatch': {
      id: '/api/public/hooks/notifications-dispatch'
      path: '/api/public/hooks/notifications-dispatch'
      fullPath: '/api/public/hooks/notifications-dispatch'
      preLoaderRoute: typeof ApiPublicHooksNotificationsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/engagement-nudges': {
      id: '/api/public/hooks/engagement-nudges'
      path: '/api/public/hooks/engagement-nudges'
      fullPath: '/api/public/hooks/engagement-nudges'
      preLoaderRoute: typeof ApiPublicHooksEngagementNudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/e2e-runner': {
      id: '/api/public/hooks/e2e-runner'
      path: '/api/public/hooks/e2e-runner'
      fullPath: '/api/public/hooks/e2e-runner'
      preLoaderRoute: typeof ApiPublicHooksE2eRunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/healthcheck': {
      id: '/api/public/cron/healthcheck'
      path: '/api/public/cron/healthcheck'
      fullPath: '/api/public/cron/healthcheck'
      preLoaderRoute: typeof ApiPublicCronHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/inventory/$productId': {
      id: '/_authenticated/admin/inventory/$productId'
      path: '/inventory/$productId'
      fullPath: '/admin/inventory/$productId'
      preLoaderRoute: typeof AuthenticatedAdminInventoryProductIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers/$userId': {
      id: '/_authenticated/admin/customers/$userId'
      path: '/$userId'
      fullPath: '/admin/customers/$userId'
      preLoaderRoute: typeof AuthenticatedAdminCustomersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminCustomersRoute
    }
    '/_authenticated/admin/blog/tags': {
      id: '/_authenticated/admin/blog/tags'
      path: '/tags'
      fullPath: '/admin/blog/tags'
      preLoaderRoute: typeof AuthenticatedAdminBlogTagsRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
    '/_authenticated/admin/blog/programaticas': {
      id: '/_authenticated/admin/blog/programaticas'
      path: '/programaticas'
      fullPath: '/admin/blog/programaticas'
      preLoaderRoute: typeof AuthenticatedAdminBlogProgramaticasRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
    '/_authenticated/admin/blog/new': {
      id: '/_authenticated/admin/blog/new'
      path: '/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AuthenticatedAdminBlogNewRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
    '/_authenticated/admin/blog/comentarios': {
      id: '/_authenticated/admin/blog/comentarios'
      path: '/comentarios'
      fullPath: '/admin/blog/comentarios'
      preLoaderRoute: typeof AuthenticatedAdminBlogComentariosRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
    '/_authenticated/admin/blog/categorias': {
      id: '/_authenticated/admin/blog/categorias'
      path: '/categorias'
      fullPath: '/admin/blog/categorias'
      preLoaderRoute: typeof AuthenticatedAdminBlogCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
    '/_authenticated/admin/blog/$id': {
      id: '/_authenticated/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
    '/_authenticated/dashboard/proxy/$id/quick': {
      id: '/_authenticated/dashboard/proxy/$id/quick'
      path: '/dashboard/proxy/$id/quick'
      fullPath: '/dashboard/proxy/$id/quick'
      preLoaderRoute: typeof AuthenticatedDashboardProxyIdQuickRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminBlogRouteChildren {
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminBlogCategoriasRoute: typeof AuthenticatedAdminBlogCategoriasRoute
  AuthenticatedAdminBlogComentariosRoute: typeof AuthenticatedAdminBlogComentariosRoute
  AuthenticatedAdminBlogNewRoute: typeof AuthenticatedAdminBlogNewRoute
  AuthenticatedAdminBlogProgramaticasRoute: typeof AuthenticatedAdminBlogProgramaticasRoute
  AuthenticatedAdminBlogTagsRoute: typeof AuthenticatedAdminBlogTagsRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
}

const AuthenticatedAdminBlogRouteChildren: AuthenticatedAdminBlogRouteChildren =
  {
    AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
    AuthenticatedAdminBlogCategoriasRoute:
      AuthenticatedAdminBlogCategoriasRoute,
    AuthenticatedAdminBlogComentariosRoute:
      AuthenticatedAdminBlogComentariosRoute,
    AuthenticatedAdminBlogNewRoute: AuthenticatedAdminBlogNewRoute,
    AuthenticatedAdminBlogProgramaticasRoute:
      AuthenticatedAdminBlogProgramaticasRoute,
    AuthenticatedAdminBlogTagsRoute: AuthenticatedAdminBlogTagsRoute,
    AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
  }

const AuthenticatedAdminBlogRouteWithChildren =
  AuthenticatedAdminBlogRoute._addFileChildren(
    AuthenticatedAdminBlogRouteChildren,
  )

interface AuthenticatedAdminCustomersRouteChildren {
  AuthenticatedAdminCustomersUserIdRoute: typeof AuthenticatedAdminCustomersUserIdRoute
}

const AuthenticatedAdminCustomersRouteChildren: AuthenticatedAdminCustomersRouteChildren =
  {
    AuthenticatedAdminCustomersUserIdRoute:
      AuthenticatedAdminCustomersUserIdRoute,
  }

const AuthenticatedAdminCustomersRouteWithChildren =
  AuthenticatedAdminCustomersRoute._addFileChildren(
    AuthenticatedAdminCustomersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAllocationsRoute: typeof AuthenticatedAdminAllocationsRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRouteWithChildren
  AuthenticatedAdminBroadcastRoute: typeof AuthenticatedAdminBroadcastRoute
  AuthenticatedAdminChatRoute: typeof AuthenticatedAdminChatRoute
  AuthenticatedAdminCloudRoute: typeof AuthenticatedAdminCloudRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRouteWithChildren
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
  AuthenticatedAdminProviderRoute: typeof AuthenticatedAdminProviderRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminInventoryProductIdRoute: typeof AuthenticatedAdminInventoryProductIdRoute
  AuthenticatedAdminInventoryIndexRoute: typeof AuthenticatedAdminInventoryIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAllocationsRoute: AuthenticatedAdminAllocationsRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRouteWithChildren,
  AuthenticatedAdminBroadcastRoute: AuthenticatedAdminBroadcastRoute,
  AuthenticatedAdminChatRoute: AuthenticatedAdminChatRoute,
  AuthenticatedAdminCloudRoute: AuthenticatedAdminCloudRoute,
  AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
  AuthenticatedAdminCustomersRoute:
    AuthenticatedAdminCustomersRouteWithChildren,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
  AuthenticatedAdminProviderRoute: AuthenticatedAdminProviderRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminInventoryProductIdRoute:
    AuthenticatedAdminInventoryProductIdRoute,
  AuthenticatedAdminInventoryIndexRoute: AuthenticatedAdminInventoryIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardNotificacoesRoute: typeof AuthenticatedDashboardNotificacoesRoute
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardProxiesRoute: typeof AuthenticatedDashboardProxiesRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardProxyIdQuickRoute: typeof AuthenticatedDashboardProxyIdQuickRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardNotificacoesRoute:
    AuthenticatedDashboardNotificacoesRoute,
  AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
  AuthenticatedDashboardProxiesRoute: AuthenticatedDashboardProxiesRoute,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardProxyIdQuickRoute:
    AuthenticatedDashboardProxyIdQuickRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCSlugRoute: typeof BlogCSlugRoute
  BlogTagSlugRoute: typeof BlogTagSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogCSlugRoute: BlogCSlugRoute,
  BlogTagSlugRoute: BlogTagSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ReembolsoRoute: ReembolsoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicCronHealthcheckRoute: ApiPublicCronHealthcheckRoute,
  ApiPublicHooksE2eRunnerRoute: ApiPublicHooksE2eRunnerRoute,
  ApiPublicHooksEngagementNudgesRoute: ApiPublicHooksEngagementNudgesRoute,
  ApiPublicHooksNotificationsDispatchRoute:
    ApiPublicHooksNotificationsDispatchRoute,
  ApiPublicHooksProxysellerBackfillRoute:
    ApiPublicHooksProxysellerBackfillRoute,
  ApiPublicHooksProxysellerSyncRoute: ApiPublicHooksProxysellerSyncRoute,
  ApiPublicHooksStripeSyncRoute: ApiPublicHooksStripeSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
