/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated.dashboard.settings'
import { Route as AuthenticatedDashboardProxiesRouteImport } from './routes/_authenticated.dashboard.proxies'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated.dashboard.orders'
import { Route as AuthenticatedAdminProviderRouteImport } from './routes/_authenticated.admin.provider'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated.admin.orders'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated.admin.inventory'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated.admin.emails'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated.admin.customers'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProxiesRoute =
  AuthenticatedDashboardProxiesRouteImport.update({
    id: '/proxies',
    path: '/proxies',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminProviderRoute =
  AuthenticatedAdminProviderRouteImport.update({
    id: '/provider',
    path: '/provider',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/provider': typeof AuthenticatedAdminProviderRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/proxies': typeof AuthenticatedDashboardProxiesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/provider': typeof AuthenticatedAdminProviderRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/proxies': typeof AuthenticatedDashboardProxiesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/provider': typeof AuthenticatedAdminProviderRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/proxies': typeof AuthenticatedDashboardProxiesRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/checkout/success'
    | '/admin/customers'
    | '/admin/emails'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/provider'
    | '/dashboard/orders'
    | '/dashboard/proxies'
    | '/dashboard/settings'
    | '/api/public/stripe-webhook'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/checkout/success'
    | '/admin/customers'
    | '/admin/emails'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/provider'
    | '/dashboard/orders'
    | '/dashboard/proxies'
    | '/dashboard/settings'
    | '/api/public/stripe-webhook'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/checkout/success'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/provider'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/proxies'
    | '/_authenticated/dashboard/settings'
    | '/api/public/stripe-webhook'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/proxies': {
      id: '/_authenticated/dashboard/proxies'
      path: '/proxies'
      fullPath: '/dashboard/proxies'
      preLoaderRoute: typeof AuthenticatedDashboardProxiesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/provider': {
      id: '/_authenticated/admin/provider'
      path: '/provider'
      fullPath: '/admin/provider'
      preLoaderRoute: typeof AuthenticatedAdminProviderRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProviderRoute: typeof AuthenticatedAdminProviderRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminProviderRoute: AuthenticatedAdminProviderRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardProxiesRoute: typeof AuthenticatedDashboardProxiesRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
    AuthenticatedDashboardProxiesRoute: AuthenticatedDashboardProxiesRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
